### ISSUE TITLE
OPENMP - Dense vs Sparse

### ISSUE THREAD

**Issue by hofert** [yixuan/arpack-arma#1]
Hello,

First a big thank you for putting up such a brilliant piece of code. I tested arpack-arma last week the first time and it nicely worked in an arpack-arma -> armadillo -> openblas "construct".

Following the examples is also straightforward and I am crunching huge test matrices on my workspace computer... 

One very convenient thing was that the OpenMP  support of OpenBlas works nicely in armadillo and arpack-arma when computing eigenvalues for dense matrices using DenseGenMatProd and SymEigsSolver.

When switching to SparseGenMatProd in SymEigsSolver it seems only single-CPU execution is working (according to top and the runtime). Basically I just changed all "Dense" to "Sparse" including the header and I am feeding an armadillo sp_mat to  SparseGenMatProd<double> op(Bsp). Eigenvalues/Eigenvectors are fine, though. Since I am not exactly an expert in reading your rather advanced code, I am not sure if something is missing in my program....? 

This should not be a feature request - I just want to avoid spending coding effort into the wrong direction, if OMP is not working with SparseGenMatProd.

Many thanks and best regards,
Thomas

**Comment by yixuan** [comment]
Hi Tom,

Basically arpack-arma is a single-core program. The parallelism you see in dense eigenvalue computation comes from the matrix-vector operation in OpenBlas. As for sparse matrices, the matrix-vector operation is not coming from OpenBlas, but from Armadillo, which is actually single-threaded.

Does this explain your question?

Best,
Yixuan

**Comment by hofert** [comment]
Hi Yixuan,

Thanks for the quick response. I suspected something like this. The OMP for sparsity would have been nice, but the code is still quite fast even in single CPU mode.

I want to ask about the performance of the other libraries on your page compared to arpack-arma. Is there a gain in performance when switching for example to specta or are the performances for eigensystems comparable?

Thanks and best wishes,
Thomas

**Comment by yixuan** [comment]
Spectra (previously arpack-eigen) is a direct translation of arpack-arma using the Eigen library. Given that Eigen utilizes some advanced CPU features like vectorization, it can be slightly faster than the Armadillo-based arpack-arma, but according to my experience the difference is small, especially for large matrices.

Perhaps the major difference is that I tend to be more active on the development of Spectra, so usually it is more up-to-date than arpack-arma.

Best,
Yixuan
