### ISSUE TITLE
Which version of armadillo is required?

### ISSUE THREAD

**Issue by kingfisher1337** [yixuan/arpack-arma#2]
I just downloaded armadillo (stable version 8.100) and arpack-arma and tried to compile the sample program of the arpack-arma readme (attached below for clarity). Unfortunately, I get compilation errors, starting as follows.
```
In file included from /home/michael/Documents/test/cpp/arpack_arma/arpack-arma/include/LinAlg/TridiagEigen.h:12:0,
                 from /home/michael/Documents/test/cpp/arpack_arma/arpack-arma/include/SymEigsSolver.h:19,
                 from test3.cpp:2:
/home/michael/Documents/test/cpp/arpack_arma/arpack-arma/include/LinAlg/LapackWrapperExtra.h:94:9: error: redefinition of ‘template<class eT> void arma::lapack::sytrs(char*, arma::blas_int*, arma::blas_int*, eT*, arma::blas_int*, arma::blas_int*, eT*, arma::blas_int*, arma::blas_int*)’
         sytrs(char* uplo, blas_int* n, blas_int* nrhs, eT* a, blas_int* lda, blas_int* ipiv, eT* b, blas_int* ldb, blas_int* info)
         ^
...
```
What is the lastest version of armadillo I can use to build arpack-arma? Or is there a way to use the latest version of armadillo?
Thanks in advance!

```
#include <armadillo>
#include <SymEigsSolver.h>  // Also includes <MatOp/DenseGenMatProd.h>

int main()
{
    // We are going to calculate the eigenvalues of M
    arma::mat A = arma::randu(10, 10);
    arma::mat M = A + A.t();

    // Construct matrix operation object using the wrapper class DenseGenMatProd
    DenseGenMatProd<double> op(M);

    // Construct eigen solver object, requesting the largest three eigenvalues
    SymEigsSolver< double, LARGEST_ALGE, DenseGenMatProd<double> > eigs(&op, 3, 6);

    // Initialize and compute
    eigs.init();
    int nconv = eigs.compute();

    // Retrieve results
    arma::vec evalues;
    if(nconv > 0)
     evalues = eigs.eigenvalues();

    evalues.print("Eigenvalues found:");

    return 0;
}
```

**Comment by rcurtin** [comment]
Isn't arpack-arma integrated into Armadillo now? I am not sure you need to use this pronect separately.

**Comment by kingfisher1337** [comment]
As far as I can see, armadillo has only the function `eigs_gen` for general sparse eigenvalue problems. This function only can deal with objects of type `SpMat`, which are basically matrices in CSC format, but I need to implement the matrix-vector product myself.

**Comment by rcurtin** [comment]
Take a look in `include/armadillo_bits/`, I think all of the arpack-arma code is in there and you could use it directly.  It's not documented on the Armadillo documentation though so you will have to do a little exploring of what is there.

**Comment by yixuan** [comment]
Yeah, as Ryan mentioned, you can use arpack-arma "internally" by adding the `arma::newarp` namespace. Below is the revised example code:

```cpp
#include <armadillo>
using namespace arma::newarp;

int main()
{
    // We are going to calculate the eigenvalues of M
    arma::mat A = arma::randu(10, 10);
    arma::mat M = A + A.t();

    // Construct matrix operation object using the wrapper class DenseGenMatProd
    DenseGenMatProd<double> op(M);

    // Construct eigen solver object, requesting the largest three eigenvalues
    SymEigsSolver< double, EigsSelect::LARGEST_ALGE, DenseGenMatProd<double> > eigs(op, 3, 6);

    // Initialize and compute
    eigs.init();
    int nconv = eigs.compute();

    // Retrieve results
    arma::vec evalues;
    if(nconv > 0)
     evalues = eigs.eigenvalues();

    evalues.print("Eigenvalues found:");

    return 0;
}
```

Apart from the namespace, there are two noticeable changes:
1. Selection rule enumerations are inside the `EigsSelect` class.
2. Pass `op` rather than `&op` to the constructor.

**Comment by kingfisher1337** [comment]
Thank you very much for your help! The only thing I really cannot understand: Why is this absolutely great feature in armadillo not documented?

**Comment by yixuan** [comment]
@kingfisher1337 The code was used to implement the Armadillo API functions `eigs_sym()` and `eigs_gen()`. Armadillo is designed to provide high-level functions in numerical computing, and my code was a bit too low-level.

**Comment by d-wiater** [comment]
I would like to ask about DenseSymShiftSolve.
It seems to me that mentioned procedure does not work.

Compiler does not see DenseSymShiftSolve and SymEigsShiftSolver.

Furthermore when I tried  use arpack-arma I had the same  errors. 

Does anyone know how to run this package?

**Comment by yixuan** [comment]
@dw93 These two are not integrated into Armadillo. You can consider using [Spectra](https://github.com/yixuan/spectra) instead.

**Comment by d-wiater** [comment]
@yixuan Thank you very much for response.

I used Spectra and everything works very well, but I have additional question about parallelization.
I noticed that in armadillo computations were automatically parallel, but in Spectra It did not take place.

Is there any method to force Spectra to be parallel?

**Comment by yixuan** [comment]
@dw93 Armadillo uses BLAS for automatic parallelization, and Spectra is based on Eigen. You can configure Eigen to use BLAS for matrix operations as well, see [this page](http://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html).

However, the major computation that happens in the algorithm is matrix-vector multiplication, which may not benefit from parallelization much.

Since the original question of this issue has been answered, let me close it for now.
